#!/bin/bash

# BEGIN ANSIBLE MANAGED BLOCK : direnv
sudo cgroupfs-mount
sudo usermod -aG docker $USER
sudo service docker start
# END ANSIBLE MANAGED BLOCK : docker

# BEGIN ANSIBLE MANAGED BLOCK : direnv
export EDITOR=vim
eval $(direnv hook bash)
# END ANSIBLE MANAGED BLOCK : direnv

# BEGIN ANSIBLE MANAGED BLOCK : pyenv
export PYENV_ROOT="/home/guitarrapc/pyenv"
export PATH="/home/guitarrapc/pyenv/shims:/home/guitarrapc/pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# END ANSIBLE MANAGED BLOCK : pyenv