name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      sh-debug:
        description: "enable debug on install.sh"
        default: "-x"

env:
  SH_DEBUG: ${{ github.event_name == 'workflow_dispath' && inputs.sh-debug || '' }}

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    permissions:
      contents: read
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dotfiles
        run: bash ${SH_DEBUG} ./install.sh --force ${{ matrix.force }}
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test installed files
        run: |
          set -eo pipefail
          # Check if .gitconfig exists and is a symlink
          if [[ -L "$HOME/.gitconfig" && "$(readlink -f "$HOME/.gitconfig")" == "${{ github.workspace }}/.gitconfig" ]]; then
            echo ".gitconfig is correctly linked"
          else
            echo "::error::.gitconfig is missing or not linked correctly" && exit 1
          fi
