name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      sh-debug:
        description: "enable debug on install.sh"
        default: "-x"

env:
  SH_DEBUG: ${{ github.event_name == 'workflow_dispath' && inputs.sh-debug || '' }}

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    permissions:
      contents: read
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install dotfiles
        run: bash ${SH_DEBUG} ./install.sh --force ${{ matrix.force }}
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test file located as expected
        run: |
          set -eo pipefail
          # Check if .config/git/config exists and is a symlink
          if [[ -L "$HOME/.config/git/config" && "$(readlink -f "$HOME/.config/git/config")" == "${{ github.workspace }}/HOME/.config/git/config" ]]; then
            echo ".config/git/config is correctly linked"
          else
            echo "::error::.config/git/config is missing or not linked correctly" && exit 1
          fi
